In [1]:
import pandas as pd

In [6]:
titanic=pd.read_csv('test.csv')
titanic

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [8]:
titanic_small = titanic[['Age','SibSp','Parch']].iloc[:10]
titanic_small

Age  SibSp  Parch
0  34.5      0      0
1  47.0      1      0
2  62.0      0      0
3  27.0      0      0
4  22.0      1      1
5  14.0      0      0
6  30.0      0      0
7  26.0      1      1
8  18.0      0      0
9  21.0      2      0

In [9]:
import numpy as np

In [12]:
titanic_array = np.array(titanic_small)

In [11]:
np.array(['hello'])

array(['hello'], dtype='<U5')

In [14]:
np.save('titanic.npy', titanic_array)

In [15]:
titanic_array_load = np.load('titanic.npy')

In [16]:
titanic_array_load == titanic_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##실습

In [45]:
np.save('df_to_arr.npy', titanic.T.iloc[-3])

In [19]:
titanic.T.iloc[-3]

0       7.8292
1          7.0
2       9.6875
3       8.6625
4      12.2875
        ...   
413       8.05
414      108.9
415       7.25
416       8.05
417    22.3583
Name: Fare, Length: 418, dtype: object

In [33]:
df_to_arr_load = np.load('df_to_arr.npy',allow_pickle=True)
df_to_arr_load

array([7.8292, 7.0, 9.6875, 8.6625, 12.2875, 9.225, 7.6292, 29.0, 7.2292,
       24.15, 7.8958, 26.0, 82.2667, 26.0, 61.175, 27.7208, 12.35, 7.225,
       7.925, 7.225, 59.4, 3.1708, 31.6833, 61.3792, 262.375, 14.5,
       61.9792, 7.225, 30.5, 21.6792, 26.0, 31.5, 20.575, 23.45, 57.75,
       7.2292, 8.05, 8.6625, 9.5, 56.4958, 13.4167, 26.55, 7.85, 13.0,
       52.5542, 7.925, 29.7, 7.75, 76.2917, 15.9, 60.0, 15.0333, 23.0,
       263.0, 15.5792, 29.125, 7.8958, 7.65, 16.1, 262.375, 7.8958, 13.5,
       7.75, 7.725, 262.375, 21.0, 7.8792, 42.4, 28.5375, 263.0, 7.75,
       7.8958, 7.925, 27.7208, 211.5, 211.5, 8.05, 25.7, 13.0, 7.75,
       15.2458, 221.7792, 26.0, 7.8958, 10.7083, 14.4542, 7.8792, 8.05,
       7.75, 23.0, 13.9, 7.775, 52.0, 8.05, 26.0, 7.7958, 78.85, 7.925,
       7.8542, 8.05, 55.4417, 26.0, 7.75, 7.775, 8.5167, 22.525, 7.8208,
       7.75, 8.7125, 13.0, 15.0458, 7.7792, 31.6792, 7.2833, 221.7792,
       14.4542, 6.4375, 16.7, 75.2417, 26.0, 15.75, 7.75, 57.75, 7.2

In [44]:
df_to_arr_load[2:5].dot(df_to_arr_load[7:10])

640.30357

##실습정답

In [47]:
to_file = np.array(titanic['Fare'])
to_file

array([  7.8292,   7.    ,   9.6875,   8.6625,  12.2875,   9.225 ,
         7.6292,  29.    ,   7.2292,  24.15  ,   7.8958,  26.    ,
        82.2667,  26.    ,  61.175 ,  27.7208,  12.35  ,   7.225 ,
         7.925 ,   7.225 ,  59.4   ,   3.1708,  31.6833,  61.3792,
       262.375 ,  14.5   ,  61.9792,   7.225 ,  30.5   ,  21.6792,
        26.    ,  31.5   ,  20.575 ,  23.45  ,  57.75  ,   7.2292,
         8.05  ,   8.6625,   9.5   ,  56.4958,  13.4167,  26.55  ,
         7.85  ,  13.    ,  52.5542,   7.925 ,  29.7   ,   7.75  ,
        76.2917,  15.9   ,  60.    ,  15.0333,  23.    , 263.    ,
        15.5792,  29.125 ,   7.8958,   7.65  ,  16.1   , 262.375 ,
         7.8958,  13.5   ,   7.75  ,   7.725 , 262.375 ,  21.    ,
         7.8792,  42.4   ,  28.5375, 263.    ,   7.75  ,   7.8958,
         7.925 ,  27.7208, 211.5   , 211.5   ,   8.05  ,  25.7   ,
        13.    ,   7.75  ,  15.2458, 221.7792,  26.    ,   7.8958,
        10.7083,  14.4542,   7.8792,   8.05  ,   7.75  ,  23. 

In [48]:
np.save('df_to_arr.npy', to_file)

In [49]:
titanic_small = titanic[['Age','SibSp','Parch']].iloc[:10]

In [52]:
array_dot1 = np.array(titanic_small.iloc[:3])
array_dot1

array([[34.5,  0. ,  0. ],
       [47. ,  1. ,  0. ],
       [62. ,  0. ,  0. ]])

In [55]:
array_dot2 = np.array(titanic_small.iloc[-3:])
array_dot2

array([[26.,  1.,  1.],
       [18.,  0.,  0.],
       [21.,  2.,  0.]])

In [56]:
array_dot1.dot(array_dot2)

array([[ 897. ,   34.5,   34.5],
       [1240. ,   47. ,   47. ],
       [1612. ,   62. ,   62. ]])

In [72]:
for i in titanic_small.index:
    print(titanic_small.iloc[i,1])

0
1
0
0
1
0
0
1
0
2


In [68]:
i=0
while :
    print(titanic_small.iloc[i,1]))
    i +=1

7.8292
7.0
9.6875
8.6625
12.2875
9.225
7.6292
29.0
7.2292
24.15


In [5]:
def plus(x, y):
    return x + y
plus(1,1)

In [9]:
def append2(l2):
   global l1

[1, 2, 3, 4, 5]


In [10]:
import pandas as pd

In [11]:
df=pd.read_csv('test.csv')

In [12]:
df.head(2)

PassengerId  Pclass                              Name     Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    male  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   

   Parch  Ticket    Fare Cabin Embarked  
0      0  330911  7.8292   NaN        Q  
1      0  363272  7.0000   NaN        S

In [19]:
fn1=0
for i in df.index:
    df.iloc[i,-7]>=20
    fn1+=1
fn1

418

In [31]:
def fn1(i):
    return i>=20
df['Age']=[fn1(i) for i in df['Age']]
df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex    Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  False      0      0              330911    7.8292   NaN        Q  
1    female  False      1      0              363272    7.0000   NaN        S  
2      male  False      0      0              240276    9.6875   NaN        Q  
3      male  False      0      0              315154    8.6625   NaN        S  
4    female  False      1      1             3101298   12.2875   NaN        S  
..      ...    ...    ...    ...                 ...       ...   ...      ...  
413    male  False      0      0           A.5. 3236    8.0500   NaN        S  
414  female  False      0      0            PC 17758  108.9000  C105        C  
415    male  False      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male  False      0      0              359309    8.0500   NaN        S  
417    male  False      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [37]:
j=0
def fn2(i):
    global j
    global df
    df.loc[j,'Age']=i>=20
    j+=1
[fn1(i) for i in df['Age']]
df

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex    Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  False      0      0              330911    7.8292   NaN        Q  
1    female  False      1      0              363272    7.0000   NaN        S  
2      male  False      0      0              240276    9.6875   NaN        Q  
3      male  False      0      0              315154    8.6625   NaN        S  
4    female  False      1      1             3101298   12.2875   NaN        S  
..      ...    ...    ...    ...                 ...       ...   ...      ...  
413    male  False      0      0           A.5. 3236    8.0500   NaN        S  
414  female  False      0      0            PC 17758  108.9000  C105        C  
415    male  False      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male  False      0      0              359309    8.0500   NaN        S  
417    male  False      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [47]:
str.count(sub[, start[, end]])

TypeError: list indices must be integers or slices, not str

In [61]:
for i in range(len(df['Name'])):
    df['Name'][i]+=df['Name'][i].count('.').count(',')
df['Name']

AttributeError: 'int' object has no attribute 'count'

In [62]:
df['Name'].index

RangeIndex(start=0, stop=418, step=1)

In [66]:
df['Name'].str.count(',')

0      1
1      1
2      1
3      1
4      1
      ..
413    1
414    1
415    1
416    1
417    1
Name: Name, Length: 418, dtype: int64

In [70]:
count_str = [nm.count(',') + nm.count('.') for nm in df['Name']]
count_blank = [nm.count(' ') >= 2 for nm in df['Name']]
print(count_str)
print(count_blank)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 